- hosts: local
  connection: local
  vars:
    RessourcesGroupe: "MonPetitRG"
    NomDeVm: "MaMachine1"
    NomDeReseau: "LeReseau"
    vn_name: "ReseauVirtuel"
    NomDuGroupeSecu: "SecuGroupe"
  roles:
    - vm
    - vnet
    - server