- hosts: localhost
  connection: local
  vars_prompt:
    - name: password
      prompt: "Enter local admin password"
      
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: rg-cs-ansible
        location: westeurope

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: rg-cs-ansible
        name: vm-cs-web01
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        admin_password: "{{ password }}"
        os_type: Linux
        image:
          offer: "UbuntuServer"
          publisher: "Canonical"
          sku: "20.04-LTS"
          version: latest
